# Generated by Django 5.0.3 on 2024-03-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_userdata_accnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Reflactor',
            new_name='Reflactorr',
        ),
    ]
